=== Oscar01am/tec_web/practicas/P12/spotify_ns.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:tw="http://tecnologiasweb.com.mx"
    targetNamespace="http://tecnologiasweb.com.mx">
    
    <xsd:element name="spotify" type="tw:spotifyType"/>
    <xsd:element name="cuenta" type="tw:cuentaType"/>
    <xsd:element name="nombre" type="xsd:string"/>
    <xsd:element name="correo" type="xsd:string"/>
    <xsd:element name="telefono" type="tw:telType"/>
    
    <xsd:attribute name="version" type="xsd:string" default=""/>
    
    <xsd:attribute name="id" type="xsd:string" default="0"/>
    <xsd:attribute name="plan" type="xsd:string" default=""/>
    <xsd:attribute name="fechaIni" type="xsd:string" default=""/>
    <xsd:attribute name="fechaFin" type="xsd:string" default=""/>
    
    <xsd:attribute name="tipo" type="xsd:string"/>
    
    
    <xsd:complexType name="spotifyType">      
        <xsd:sequence> 
            <xsd:element ref="tw:cuenta" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute ref="tw:version"/>
    </xsd:complexType>
    
    
    <xsd:complexType name="cuentaType">
        <xsd:sequence>
            <xsd:element ref="tw:nombre"/>
            <xsd:element ref="tw:correo"/>
            <xsd:element ref="tw:telefono"/> 
        </xsd:sequence>
        <xsd:attribute ref="tw:id"/>
        <xsd:attribute ref="tw:plan"/>
        <xsd:attribute ref="tw:fechaIni" use="optional"/>
        <xsd:attribute ref="tw:fechaFin" use="optional"/>
    </xsd:complexType>
    
    
    <xsd:complexType name="telType" mixed="true">
        <xsd:attribute ref="tw:tipo" use="required"/>
    </xsd:complexType>
    
</xsd:schema>

=== Oscar01am/tec_web/practicas/P12/spotify_ns.xml
<?xml version="1.0" encoding="UTF-8"?>
<tw:spotify xmlns:tw="http://tecnologiasweb.com.mx" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://tecnologiasweb.com.mx spotify_ns.xsd">
    <tw:cuenta tw:id="1" tw:plan="premium" tw:fechaIni="2022-02-01" tw:fechaFin="2023-02-01">
        <tw:nombre>Oscar Diaz</tw:nombre>
        <tw:correo>Oscaramaro.01@gmail.com</tw:correo>
        <tw:telefono tw:tipo="movil">222 678 4269</tw:telefono>
    </tw:cuenta>
    <tw:cuenta tw:id="2" tw:plan="familiar" tw:fechaIni="2023-01-21" tw:fechaFin="2024-01-21">
        <tw:nombre>Daniel Faustino</tw:nombre>
        <tw:correo>daniel98fa@gmail.com</tw:correo>
        <tw:telefono tw:tipo="casa">222 435 2674</tw:telefono>
    </tw:cuenta>
</tw:spotify>
